name: My Quarkus Continuous Integration
on: push
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set docker image name env
        run: echo ::set-env name=DOCKER_IMAGE_NAME::chrisbalcita/isspages

      - name: Set docker image tag env
        run: echo ::set-env name=DOCKER_TAG_VERSION::$(echo $GITHUB_RUN_NUMBER)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./src/main/docker
          file: ./Dockerfile
          push: true
          tags: |
            chrisbalcita/isspages:latest
            chrisbalcita/isspages:${{ github.run_number }}