name: My Quarkus Continuous Integration
on: push
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v2

      - name: mvn -v
        run: mvn -v

      - name: java -v
        run: java -version

      - name: mvnw permission
        run: chmod +x

      - name: Maven build
        run: /mvnw package

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            chrisbalcita/isspages:latest
            chrisbalcita/isspages:${{ github.run_number }}